#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

umask 077

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
ARTIFACT_ROOT="${ICARUS_GATE1_ARTIFACT_ROOT:-$REPO_ROOT/.local/gate1-live}"
LIVE_ROOT="${ICARUS_GATE1_LIVE_ROOT:-${XDG_STATE_HOME:-$HOME/.local/state}/icarus-gate1-live}"
SOURCES_ROOT="$LIVE_ROOT/sources"
ICARUS_HOME="$LIVE_ROOT/state"
ENV_FILE="$ARTIFACT_ROOT/wizard.env"
MANIFEST="$ARTIFACT_ROOT/manifest.v1.json"
PROFILE_DRAFT="$ARTIFACT_ROOT/profile-draft.v1.json"
PROFILE_APPROVED="$ARTIFACT_ROOT/profile-approved.v1.json"
RUN_MAP="$ARTIFACT_ROOT/runs.v1.json"
ARTIFACT_HELPER="$REPO_ROOT/scripts/gate1-live-3of3-artifacts.mjs"
ICARUS_CLI="$REPO_ROOT/packages/cli/dist/main.js"
SOURCE_MANIFEST="$REPO_ROOT/fixtures/evals/gate1/manifest.v1.json"
OWNER="ayyitskevin"
MODEL="qwen3.8:27b"
BASE_URL="http://127.0.0.1:11434/"
TOKEN_ENV="ICARUS_GITHUB_TOKEN_GATE1"
export ICARUS_GITHUB_TOKEN_ALLOWLIST="$TOKEN_ENV"

CASES=("typescript-library-repair" "python-cli-repair" "react-node-repair")
STACKS=("typescript-library" "python-cli" "react-node")
REPOSITORIES=("icarus-gate1-typescript-library" "icarus-gate1-python-cli" "icarus-gate1-react-node")
RUN_KEYS=("TYPESCRIPT_RUN_ID" "PYTHON_RUN_ID" "REACT_RUN_ID")

die() {
  printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || die "required command is unavailable: $1"
}

checkpoint() { printf '%s/stage-%s.done' "$ARTIFACT_ROOT" "$1"; }
stage_done() { [[ -f "$(checkpoint "$1")" ]]; }
mark_stage() { printf 'ok\n' > "$(checkpoint "$1")"; chmod 600 "$(checkpoint "$1")"; }

icarus() {
  ICARUS_HOME="$ICARUS_HOME" node "$ICARUS_CLI" "$@"
}

fixture_git() {
  local repository="$1" control_home="$2"
  shift 2
  env -i \
    PATH=/usr/bin:/bin HOME="$control_home" XDG_CONFIG_HOME="$control_home" \
    LANG=C.UTF-8 LC_ALL=C.UTF-8 GIT_CONFIG_NOSYSTEM=1 GIT_CONFIG_GLOBAL=/dev/null \
    GIT_ATTR_NOSYSTEM=1 GIT_TERMINAL_PROMPT=0 GIT_ASKPASS=/bin/false \
    GIT_SSH_COMMAND=false GIT_PAGER=cat GIT_OPTIONAL_LOCKS=0 \
    GIT_AUTHOR_NAME="Icarus Gate 1 Fixture" \
    GIT_AUTHOR_EMAIL=icarus-gate1-fixture@example.invalid \
    GIT_COMMITTER_NAME="Icarus Gate 1 Fixture" \
    GIT_COMMITTER_EMAIL=icarus-gate1-fixture@example.invalid \
    GIT_AUTHOR_DATE=2000-01-01T00:00:00Z GIT_COMMITTER_DATE=2000-01-01T00:00:00Z \
    /usr/bin/git --no-pager --no-replace-objects \
      -c core.fsmonitor=false -c core.hooksPath=/dev/null \
      -c core.attributesFile=/dev/null -c credential.helper= \
      -c protocol.allow=never -c protocol.file.allow=always \
      -c protocol.ext.allow=never -C "$repository" "$@"
}

verify_source() {
  local source="$1" expected_commit="$2" expected_tree="$3" control_home="$4"
  [[ "$(fixture_git "$source" "$control_home" rev-parse HEAD)" == "$expected_commit" ]] ||
    die "$source does not have the pinned source commit"
  [[ "$(fixture_git "$source" "$control_home" rev-parse 'HEAD^{tree}')" == "$expected_tree" ]] ||
    die "$source does not have the pinned source tree"
  [[ -z "$(fixture_git "$source" "$control_home" status --porcelain=v1 --untracked-files=all)" ]] ||
    die "$source is not clean"
}

api_array_count() {
  gh api --paginate "$1" --jq '.[].id' | wc -l | tr -d ' '
}

verify_live_inert_current() {
  local index repository case_id expected_commit remote_sha workflow_files
  for index in "${!CASES[@]}"; do
    repository="${REPOSITORIES[$index]}"
    case_id="${CASES[$index]}"
    expected_commit=$(jq -r --arg id "$case_id" '.cases[] | select(.id == $id) | .repository.sourceRevision.commitSha1' "$MANIFEST")
    remote_sha=$(gh api "repos/$OWNER/$repository/git/ref/heads/main" --jq .object.sha)
    [[ "$(gh repo view "$OWNER/$repository" --json isPrivate --jq .isPrivate)" == "true" ]] ||
      die "$OWNER/$repository is no longer private"
    [[ "$(gh api "repos/$OWNER/$repository/actions/permissions" --jq .enabled)" == "false" ]] ||
      die "Actions are no longer disabled for $OWNER/$repository"
    [[ "$remote_sha" == "$expected_commit" ]] ||
      die "$OWNER/$repository main no longer matches the pinned fixture"
    [[ "$(api_array_count "repos/$OWNER/$repository/hooks")" == "0" ]] ||
      die "$OWNER/$repository now has webhooks"
    [[ "$(gh api "repos/$OWNER/$repository/actions/secrets" --jq .total_count)" == "0" ]] ||
      die "$OWNER/$repository now has Actions secrets"
    [[ "$(gh api "repos/$OWNER/$repository/environments" --jq .total_count)" == "0" ]] ||
      die "$OWNER/$repository now has environments"
    [[ "$(api_array_count "repos/$OWNER/$repository/deployments")" == "0" ]] ||
      die "$OWNER/$repository now has deployments"
    workflow_files=0
    if [[ -d "$SOURCES_ROOT/${STACKS[$index]}/.github/workflows" ]]; then
      workflow_files=$(find "$SOURCES_ROOT/${STACKS[$index]}/.github/workflows" -type f | wc -l | tr -d ' ')
    fi
    [[ "$workflow_files" == "0" ]] || die "$OWNER/$repository now contains workflow files"
  done
}

banner "Icarus Gate 1 · live 3/3"

stage "Preflight and isolated paths"
for command in bash node pnpm git gh jq curl docker find; do require_command "$command"; done
[[ "$(uname -s)" == "Linux" ]] || die "this first live campaign is Linux-only"
mkdir -p "$ARTIFACT_ROOT" "$LIVE_ROOT" "$SOURCES_ROOT" "$LIVE_ROOT/control-home"
chmod 700 "$ARTIFACT_ROOT" "$LIVE_ROOT" "$SOURCES_ROOT" "$LIVE_ROOT/control-home"
touch "$ENV_FILE"; chmod 600 "$ENV_FILE"
case "$(realpath -m "$ICARUS_HOME")" in
  "$(realpath -m "$REPO_ROOT")"/*) die "ICARUS_HOME must be outside the Git checkout" ;;
esac
git -C "$REPO_ROOT" merge-base --is-ancestor 6b4f8f039cc800687f8a8b0b8f3f3bebc86a5408 HEAD ||
  die "this checkout does not contain the shipped Gate 1 executor"
gh auth status >/dev/null 2>&1 || die "gh is not authenticated"
ACTOR=$(gh api user --jq '.login | ascii_downcase')
[[ "$ACTOR" == "$OWNER" ]] || die "gh is authenticated as $ACTOR, expected $OWNER"
curl -fsS "${BASE_URL}api/tags" | jq -e --arg model "$MODEL" 'any(.models[]; .name == $model)' >/dev/null ||
  die "Ollama model $MODEL is not available at $BASE_URL"
docker info >/dev/null 2>&1 || die "Docker is not ready"
pnpm --dir "$REPO_ROOT" build:node
PROFILE_ID=$(_existing PROFILE_ID || true)
if [[ -z "$PROFILE_ID" ]]; then PROFILE_ID="gate1-live-3of3-$(date -u +%Y%m%d)-v1"; fi
write_env PROFILE_ID "$PROFILE_ID"
write_env LIVE_ROOT "$LIVE_ROOT"
write_env ACTOR "$ACTOR"
note "Artifacts: $ARTIFACT_ROOT"
note "Icarus state: $ICARUS_HOME (outside the checkout)"
mark_stage 1

stage "Create three private disposable repositories"
if stage_done 2; then
  note "repository creation was already verified"
else
  for repository in "${REPOSITORIES[@]}"; do
    if gh repo view "$OWNER/$repository" --json isPrivate,nameWithOwner >/dev/null 2>&1; then
      [[ "$(gh repo view "$OWNER/$repository" --json isPrivate --jq .isPrivate)" == "true" ]] ||
        die "$OWNER/$repository exists but is not private"
      note "reusing verified private repository $OWNER/$repository"
    else
      confirm "Create private disposable repository $OWNER/$repository?" || die "repository creation declined"
      gh repo create "$OWNER/$repository" --private --disable-issues --disable-wiki
    fi
    [[ "$(gh repo view "$OWNER/$repository" --json isPrivate --jq .isPrivate)" == "true" ]] ||
      die "$OWNER/$repository did not verify as private"
  done
  mark_stage 2
fi

stage "Disable GitHub Actions"
if stage_done 3; then
  note "Actions-disable state was already verified"
else
  for repository in "${REPOSITORIES[@]}"; do
    enabled=$(gh api "repos/$OWNER/$repository/actions/permissions" --jq .enabled)
    if [[ "$enabled" == "true" ]]; then
      confirm "Disable GitHub Actions for $OWNER/$repository?" || die "Actions disable declined"
      gh api --method PUT "repos/$OWNER/$repository/actions/permissions" -F enabled=false >/dev/null
    fi
    [[ "$(gh api "repos/$OWNER/$repository/actions/permissions" --jq .enabled)" == "false" ]] ||
      die "Actions remain enabled for $OWNER/$repository"
  done
  mark_stage 3
fi

stage "Seed pinned fixtures and record inert assessments"
if stage_done 4; then
  verify_live_inert_current
  note "fixture seeding and assessments were already verified"
else
  node "$ARTIFACT_HELPER" manifest \
    --source "$SOURCE_MANIFEST" --output "$MANIFEST" --owner "$OWNER" \
    --repo "typescript-library=${REPOSITORIES[0]}" \
    --repo "python-cli=${REPOSITORIES[1]}" \
    --repo "react-node=${REPOSITORIES[2]}"
  control_home="$LIVE_ROOT/control-home"
  for index in "${!CASES[@]}"; do
    case_id="${CASES[$index]}"; repository="${REPOSITORIES[$index]}"
    source="$SOURCES_ROOT/${STACKS[$index]}"
    fixture=$(jq -r --arg id "$case_id" '.cases[] | select(.id == $id) | .repository.fixturePath' "$MANIFEST")
    expected_commit=$(jq -r --arg id "$case_id" '.cases[] | select(.id == $id) | .repository.sourceRevision.commitSha1' "$MANIFEST")
    expected_tree=$(jq -r --arg id "$case_id" '.cases[] | select(.id == $id) | .repository.sourceRevision.treeSha1' "$MANIFEST")
    if [[ ! -d "$source/.git" ]]; then
      [[ ! -e "$source" && ! -e "$source.partial" ]] || die "inspect incomplete source path: $source"
      mkdir -p "$source.partial"
      cp -a "$REPO_ROOT/$fixture/." "$source.partial/"
      fixture_git "$source.partial" "$control_home" init --object-format=sha1 --initial-branch=main >/dev/null
      fixture_git "$source.partial" "$control_home" add --all
      fixture_git "$source.partial" "$control_home" commit --no-gpg-sign -m "fixture baseline" >/dev/null
      verify_source "$source.partial" "$expected_commit" "$expected_tree" "$control_home"
      mv "$source.partial" "$source"
    fi
    verify_source "$source" "$expected_commit" "$expected_tree" "$control_home"
    if git -C "$source" remote get-url origin >/dev/null 2>&1; then
      [[ "$(git -C "$source" remote get-url origin)" == "git@github.com:$OWNER/$repository.git" ]] ||
        die "$source has an unexpected origin"
    else
      git -C "$source" remote add origin "git@github.com:$OWNER/$repository.git"
    fi
    remote_sha=$(gh api "repos/$OWNER/$repository/git/ref/heads/main" 2>/dev/null | jq -r '.object.sha // empty' || true)
    if [[ -z "$remote_sha" ]]; then
      confirm "Push pinned fixture commit $expected_commit to $OWNER/$repository main?" || die "fixture push declined"
      git -C "$source" push origin main:main
    elif [[ "$remote_sha" != "$expected_commit" ]]; then
      die "$OWNER/$repository main is $remote_sha, expected $expected_commit; no overwrite attempted"
    fi
    remote_sha=$(gh api "repos/$OWNER/$repository/git/ref/heads/main" --jq .object.sha)
    workflow_files=0
    if [[ -d "$source/.github/workflows" ]]; then
      workflow_files=$(find "$source/.github/workflows" -type f | wc -l | tr -d ' ')
    fi
    actions_enabled=$(gh api "repos/$OWNER/$repository/actions/permissions" --jq .enabled)
    webhooks=$(api_array_count "repos/$OWNER/$repository/hooks")
    actions_secrets=$(gh api "repos/$OWNER/$repository/actions/secrets" --jq .total_count)
    environments=$(gh api "repos/$OWNER/$repository/environments" --jq .total_count)
    deployments=$(api_array_count "repos/$OWNER/$repository/deployments")
    assessed_at=$(date -u +%Y-%m-%dT%H:%M:%S.000Z)
    node "$ARTIFACT_HELPER" assessment \
      --manifest "$MANIFEST" --case "$case_id" \
      --output "$ARTIFACT_ROOT/$case_id.assessment.json" \
      --owner "$OWNER" --repository "$repository" --assessed-at "$assessed_at" \
      --private true --actions-enabled "$actions_enabled" \
      --workflow-files "$workflow_files" --webhooks "$webhooks" \
      --actions-secrets "$actions_secrets" --environments "$environments" \
      --deployments "$deployments" --remote-main-sha1 "$remote_sha"
  done
  node "$ARTIFACT_HELPER" profile \
    --manifest "$MANIFEST" --output "$PROFILE_DRAFT" --profile-id "$PROFILE_ID" \
    --actor "$ACTOR" --model "$MODEL" --base-url "$BASE_URL" \
    --assessment "${CASES[0]}=$ARTIFACT_ROOT/${CASES[0]}.assessment.json" \
    --assessment "${CASES[1]}=$ARTIFACT_ROOT/${CASES[1]}.assessment.json" \
    --assessment "${CASES[2]}=$ARTIFACT_ROOT/${CASES[2]}.assessment.json"
  mark_stage 4
fi

stage "Approve profile, complete fresh runs, and collect the token"
if [[ -f "$PROFILE_APPROVED" ]]; then
  icarus live-evidence verify --input "$PROFILE_APPROVED" --manifest "$MANIFEST" >/dev/null
  note "reusing the already verified approved profile"
else
  say "Review the exact zero-spend profile and its four allowed GitHub effects."
  jq '{profileId, provider, budgets, authorizedEffects, cases}' "$PROFILE_DRAFT"
  icarus live-evidence digest --input "$PROFILE_DRAFT"
  confirm "Approve this exact profile for one disposable 3/3 campaign?" || die "profile approval declined"
  approved_tmp=$(mktemp "$ARTIFACT_ROOT/.profile-approved.XXXXXX")
  icarus live-evidence approve --input "$PROFILE_DRAFT" --manifest "$MANIFEST" --actor "$ACTOR" > "$approved_tmp"
  chmod 600 "$approved_tmp"
  mv "$approved_tmp" "$PROFILE_APPROVED"
  icarus live-evidence verify --input "$PROFILE_APPROVED" --manifest "$MANIFEST" >/dev/null
fi

if ! stage_done 5; then
  icarus init >/dev/null
  for index in "${!CASES[@]}"; do
    case_id="${CASES[$index]}"; stack="${STACKS[$index]}"; repository="${REPOSITORIES[$index]}"
    run_key="${RUN_KEYS[$index]}"; existing_run=$(_existing "$run_key" || true)
    if [[ -n "$existing_run" ]]; then
      [[ "$(icarus run status "$existing_run" | jq -r .state)" == "completed" ]] ||
        die "$run_key is recorded but is not completed"
      continue
    fi
    repo_name="gate1-$stack-repo"; project_name="gate1-$stack-project"; source="$SOURCES_ROOT/$stack"
    if ! icarus repo list | jq -e --arg name "$repo_name" 'any(.[]; .name == $name)' >/dev/null; then
      icarus repo add --name "$repo_name" --path "$source" >/dev/null
    fi
    if ! icarus project list | jq -e --arg name "$project_name" 'any(.[]; .name == $name)' >/dev/null; then
      mapfile -t check_args < <(jq -c --arg id "$case_id" '.cases[] | select(.id == $id) | .checks[]' "$MANIFEST")
      project_args=(project add --name "$project_name" --repo "$repo_name" --base-ref main)
      project_args+=(--sandbox-image "$(jq -r --arg id "$case_id" '.cases[] | select(.id == $id) | .sandbox.image' "$MANIFEST")")
      for check in "${check_args[@]}"; do project_args+=(--check "$check"); done
      icarus "${project_args[@]}" >/dev/null
    fi
    evidence_sha=$(jq -r --arg id "$case_id" '.cases[] | select(.caseId == $id) | .landingProfile.derivativeEffects.evidenceSha256' "$PROFILE_APPROVED")
    icarus landing profile-set --project "$project_name" --owner "$OWNER" --repository "$repository" \
      --base-branch main --credential-env "$TOKEN_ENV" --expected-actor "$ACTOR" \
      --commit-name "Icarus Gate 1 Benchmark" --commit-email icarus-gate1@example.invalid \
      --derivative-effects-disposition inert-repository \
      --derivative-effects-evidence-sha "$evidence_sha" >/dev/null
    task_path=$(jq -r --arg id "$case_id" '.cases[] | select(.id == $id) | .task.path' "$MANIFEST")
    task_sentinel=$(command cat "$REPO_ROOT/$task_path"; printf '__ICARUS_SENTINEL__')
    task=${task_sentinel%__ICARUS_SENTINEL__}
    mapfile -t targets < <(jq -r --arg id "$case_id" '.cases[] | select(.id == $id) | .selectedPaths[]' "$MANIFEST")
    plan_args=(run plan --project "$project_name" --task "$task" --provider ollama --model "$MODEL" --base-url "$BASE_URL")
    for target in "${targets[@]}"; do plan_args+=(--target "$target"); done
    run_json=$(mktemp "$ARTIFACT_ROOT/.run-$stack.XXXXXX")
    icarus "${plan_args[@]}" > "$run_json"
    run_id=$(jq -r .id "$run_json"); plan_sha=$(jq -r .planSha256 "$run_json")
    [[ "$(jq -r .state "$run_json")" == "awaiting_approval" && "$plan_sha" =~ ^[0-9a-f]{64}$ ]] ||
      die "$case_id did not reach plan approval"
    confirm "Approve the bounded $case_id plan?" || die "plan approval declined"
    icarus run approve "$run_id" --plan-sha "$plan_sha" --actor "$ACTOR" > "$run_json"
    expected_paths=$(jq -c --arg id "$case_id" '.cases[] | select(.id == $id) | .expectedChangedPaths' "$MANIFEST")
    observed_paths=$(jq -c '.verification.changedPaths' "$run_json")
    jq -e '.state == "awaiting_review" and .verification.outcome == "passed" and all(.verification.checks[]; .outcome == "passed" and .truncated == false)' "$run_json" >/dev/null ||
      die "$case_id did not produce complete passing verification"
    [[ "$observed_paths" == "$expected_paths" ]] || die "$case_id changed paths differ from the manifest"
    printf '\n%s\n' "$(jq -r .diff "$run_json")"
    confirm "The $case_id diff is exact and safe to approve?" || die "diff approval declined"
    diff_sha=$(jq -r .verification.diffSha256 "$run_json")
    icarus run review "$run_id" --decision approve --diff-sha "$diff_sha" --actor "$ACTOR" > "$run_json"
    [[ "$(jq -r .state "$run_json")" == "completed" ]] || die "$case_id did not complete"
    write_env "$run_key" "$run_id"
  done
  run_map_args=(run-map --manifest "$MANIFEST" --profile "$PROFILE_APPROVED" --output "$RUN_MAP")
  for index in "${!CASES[@]}"; do
    run_map_args+=(--run "${CASES[$index]}=$(_existing "${RUN_KEYS[$index]}")")
  done
  node "$ARTIFACT_HELPER" "${run_map_args[@]}"
  mark_stage 5
fi

say "Create a fine-grained token limited to the three disposable repositories."
step "Select resource owner Ayyitskevin and only the three icarus-gate1-* repositories."
step "Grant Metadata read, Contents read/write, and Pull requests read/write. Grant nothing else."
open_url "https://github.com/settings/personal-access-tokens/new"
ask_secret GATE1_TOKEN "Paste the fine-grained token (memory only):"
[[ ${#GATE1_TOKEN} -ge 40 && "$GATE1_TOKEN" != *[[:space:]]* ]] || die "token shape is invalid"
token_actor=$(GH_TOKEN="$GATE1_TOKEN" gh api user --jq '.login | ascii_downcase')
[[ "$token_actor" == "$ACTOR" ]] || die "runtime token belongs to $token_actor, expected $ACTOR"
export ICARUS_GITHUB_TOKEN_ALLOWLIST="$TOKEN_ENV"
export ICARUS_GITHUB_TOKEN_GATE1="$GATE1_TOKEN"
unset GATE1_TOKEN
note "The runtime token is exported only in this wizard process and was not written to disk."

stage "Execute and verify the live 3/3 campaign"
verify_live_inert_current
icarus live-evidence verify --input "$PROFILE_APPROVED" --manifest "$MANIFEST"
say "This will upload Git objects, create one absent-only icarus/* branch, open one draft PR, and record one receipt in each disposable repository."
confirm "Execute those exact live effects now?" || die "live execution declined"
execution_log="$ARTIFACT_ROOT/execution-$(date -u +%Y%m%dT%H%M%SZ).ndjson"
set +e
icarus live-evidence execute --input "$PROFILE_APPROVED" --manifest "$MANIFEST" --runs "$RUN_MAP" | tee "$execution_log"
execution_status=${PIPESTATUS[0]}
set -e
chmod 600 "$execution_log"
unset ICARUS_GITHUB_TOKEN_GATE1 ICARUS_GITHUB_TOKEN_ALLOWLIST
terminal=$(tail -n 1 "$execution_log")
if [[ $execution_status -ne 0 ]]; then
  warn "execution stopped with status $execution_status; no blind retry was attempted"
  printf '%s\n' "$terminal" | jq .
  exit "$execution_status"
fi
printf '%s\n' "$terminal" | jq -e \
  '.type == "live_evidence_terminal" and .outcome == "succeeded" and (.completedCaseIds | length) == 3' >/dev/null ||
  die "terminal receipt does not prove successful 3/3 completion"
resume_id=$(printf '%s\n' "$terminal" | jq -r .resumeId)
replay_log="$ARTIFACT_ROOT/replay-$resume_id.ndjson"
icarus live-evidence resume "$resume_id" --input "$PROFILE_APPROVED" --manifest "$MANIFEST" --runs "$RUN_MAP" > "$replay_log"
chmod 600 "$replay_log"
tail -n 1 "$replay_log" | jq -e '.outcome == "succeeded" and (.completedCaseIds | length) == 3' >/dev/null ||
  die "credential-free terminal replay did not verify"
mark_stage 6
note "3/3 succeeded. Draft PRs remain open for inspection; the wizard does not merge or delete anything."

finish
